export enum BattlerEvent {
    BATTLER_KILLED = "BATTLER_KILLED",
    BATTLER_RESPAWN = "BATTLER_RESPAWN",
    BATTLER_ATTACK = "BATTLER_ATTACKED",
    BATTLER_DAMAGED = "BATTLE_DAMAGED",
    
    BATTLER_CHANGE = "BATTLER_CHANGE",
    CONSUME = "CONSUME",
    HIT = "HIT",
}

export enum ItemEvent {
    ITEM_REQUEST = "ITEM_REQUEST",
    ITEM_GROW_UP = "ITEM_GROW_UP",
    ITEM_PICKED_UP = "ITEM_PICKED_UP",
    ITEM_DROPPED = "ITEM_DROPPED",

    FINISH_GROW_UP = "FINISH_GROW_UP",

    WEAPON_USED = "WEAPON_USED",
    CONSUMABLE_USED = "CONSUMABLE_USED",
    INVENTORY_CHANGED = "INVENTORY_CHANGED",
}

export enum ShopEvent {
    OPTION_ONE_SELECTED = "OPTION_ONE_SELECTED",
    TURRET_UPGRADED = "TURRET_UPGRADED",
    
    OPTION_TWO_SELECTED = "OPTION_TWO_SELECTED",
    OPTION_THREE_SELECTED = "OPTION_THREE_SELECTED",
    OPTION_FOUR_SELECTED = "OPTION_FOUR_SELECTED",

    PEARL_SELLED = "PEARL_SELLED"
}

export const CooldownEvent = {
    COOLDOWN_MESSAGE: "cooldownMessage"
};

export enum HudEvent {
    HEALTH_CHANGE = "HEALTH_CHANGE"
}

export enum PlayerEvent {
    PLAYER_KILLED = "PLAYER_KILLED",
    SHOP_ENTERED = "SHOP_ENTERED"
}
